### ISSUE TITLE
Newsletter signup prompt when visiting catalog page

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/squarelet#183]
We should prompt new users to join the MuckRock and Election SOS newsletters when they first visit an ERH-related page.

- The MuckRock subscriber list is through Mailchimp.
- The Election SOS subscriber list is through HubSpot.

When a user subscribes, we should handle enrollment through an API or route endpoint, passing along the form data to the appropriate mailing list.

If a user is signed in, we should be able to provide their user information automatically.

We should remember which lists the user has previously signed up for, so we don't show obnoxious signup prompts if they already subscribe, or have since unsubscribed, from a mailing list.

This could include adding a new "Mailing List" data type that allows for on-the-fly configuration of new mailing lists, but this is optional.

**Comment by amandabee** [comment]
Currently, if you check "Send me updates about the Hub" when you're applying for access, we capture that in Airtable and Election SOS grabs that list and subscribes folks to their newsletter; Zapier subscribes them to MuckRock's list. We definitely want to continue to capture signups in Airtable, rather than directly signing them up for Election SOS. 

I suspect that the easiest way to do this is probably to push subscriptions to Airtable and use Zapier to add them to MuckRock, so that Election SOS can keep using the system they've been using.

**Comment by allanlasser** [comment]
Excellent, should be straightforward to send new subs through to Airtable in whatever format you're already saving them. That seems like a good intermediate layer.

**Comment by amandabee** [comment]
You should have read access to https://airtable.com/app93Yt5cwdVWTnqn/tbll1Xe9fG8Rii6rO/viw1kFeE68e1jJOmJ?blocks=hide which is where we're storing this. I added a "Source" field -- for newsletter signups that should be, like, "Newsletter Signup" or similar.
